Program ::= { Instructions } "fin"

Instructions ::= DeclarationVariable | AssignationVariable | DeclarationFonction | BlocSi (BlocSinon)? | BlocTantQue | Affiche | AppelFonction | Renvoi

DeclarationVariable ::= Type IDENTIFIANT "=" Valeur ";"
AssignationVariable ::= IDENTIFIANT "=" Valeur ";"
DeclarationFonction ::= Type IDENTIFIANT "(" ParametresFonction* ")" "{" { Instructions } "}"
BlocSi ::= "si" "(" Condition ")" "{" { Instructions } "}"
BlocSinon ::= "sinon" "{" { Instructions } "}"
BlocTantQue ::= "tantque" "(" Condition ")" "{" { Instructions } "}"
Affiche ::= "affiche" "(" Valeur ")" ";"

Type ::= ENTIER_MOTCLE | CHAR_MOTCLE | CHAINE_MOTCLE | VIDE
Valeur ::= ENTIER | CHAR | CHAINE | IDENTIFIANT | AppelFonction
ParametresFonction ::= [ Type IDENTIFIANT { "," Type IDENTIFIANT } ]
AppelFonction ::= IDENTIFIANT "(" { ParametresAppel } ")"
ParametresAppel ::= [ Valeur { "," Valeur} ]

Condition ::= OuLogique
OuLogique ::= EtLogique { "||" EtLogique }
EtLogique ::= Egalite { "&&" Egalite }
Egalite ::= Comparaison { ("==" | "!=") Comparaison }
Comparaison ::= Addition { ("<" | "<=" | ">" | ">=") Addition }
Addition ::= Multiplication { ("+" | "-") Multiplication }
Multiplication ::= Unaire { ("*" | "/" | "%") Unaire }
Unaire ::= ("!" | "-") Unaire | Primaire
Primaire ::= Valeur | "(" Condition ")"
