Program ::= { Instructions }

Instructions ::= DeclarationVariable | AssignationVariable | DeclarationFonction | BlocSi (BlocSinon)? | BlocTantQue | Affiche | AppelFonction | Renvoi

DeclarationVariable ::= Type IDENTIFIANT "=" Condition ";"
AssignationVariable ::= IDENTIFIANT "=" Condition ";"
DeclarationFonction ::= Type IDENTIFIANT "(" { ParametresFonction } ")" "{" { Instructions } "}"
BlocSi ::= "si" "(" Condition ")" "{" { Instructions } "}"
BlocSinon ::= "sinon" "{" { Instructions } "}"
BlocTantQue ::= "tantque" "(" Condition ")" "{" { Instructions } "}"
Affiche ::= "affiche" "(" Condition ")" ";"
Renvoi ::= "renvoi" "(" Condition ")" ";"

Type ::= ENTIER_MOTCLE | CHAR_MOTCLE | CHAINE_MOTCLE | VIDE
Valeur ::= ENTIER | CHAR | CHAINE | IDENTIFIANT | AppelFonction | Condition
ParametresFonction ::= [ Type IDENTIFIANT { "," Type IDENTIFIANT } ]
AppelFonction ::= IDENTIFIANT "(" { ParametresAppel } ")"
ParametresAppel ::= [ Condition { "," Condition} ]

Condition ::= OuLogique
OuLogique ::= EtLogique { "||" EtLogique }
EtLogique ::= OuBinaire{ "&&" OuBinaire }
OuBinaire ::= EtBinaire { "|" EtBinaire }
EtBinaire ::= Egalite { "&" Egalite }
Egalite ::= Comparaison { ("==" | "!=") Comparaison }
Comparaison ::= Addition { ("<" | "<=" | ">" | ">=") Addition }
Addition ::= Multiplication { ("+" | "-") Multiplication }
Multiplication ::= Unaire { ("*" | "/" | "%") Unaire }
Unaire ::= ("!" | "-") Unaire | Primaire
Primaire ::= Valeur | "(" Condition ")"
